const typeData = {
  DRPT: "DRY \nRESISTANT \nPIGMENTED \nTIGHT",
  DRNT: "DRY \nRESISTANT \nNON-PIGMENTED \nTIGHT",
  DSPT: "DRY \nSENSITIVE \nPIGMENTED \nTIGHT",
  DSNT: "DRY \nSENSITIVE \nNON-PIGMENTED \nTIGHT",
  DRPW: "DRY \nRESISTANT \nPIGMENTED \nWRINKLED",
  DRNW: "DRY \nRESISTANT \nNON-PIGMENTED \nWRINKLED",
  DSPW: "DRY \nSENSITIVE \nPIGMENTED \nWRINKLED",
  DSNW: "DRY \nSENSITIVE \nNON-PIGMENTED \nWRINKLED",
  ORPT: "OILY \nRESISTANT \nPIGMENTED \nTIGHT",
  ORNT: "OILY \nRESISTANT \nNON-PIGMENTED \nTIGHT",
  OSPT: "OILY \nSENSITIVE \nPIGMENTED \nTIGHT",
  OSNT: "OILY \nSENSITIVE \nNON-PIGMENTED \nTIGHT",
  ORPW: "OILY \nRESISTANT \nPIGMENTED \nWRINKLED",
  ORNW: "OILY \nRESISTANT \nNON-PIGMENTED \nWRINKLED",
  OSPW: "OILY \nSENSITIVE \nPIGMENTED \nWRINKLED",
  OSNW: "OILY \nSENSITIVE \nNON-PIGMENTED \nWRINKLED",
};

export default typeData;
