const mbtiTitle = {
  DRPT: "DRY | RESISTANT | PIGMENTED | TIGHT",
  DRNT: "DRY | RESISTANT | NON-PIGMENTED | TIGHT",
  DSPT: "DRY | SENSITIVE | PIGMENTED | TIGHT",
  DSNT: "DRY | SENSITIVE | NON-PIGMENTED | TIGHT",
  DRPW: "DRY | RESISTANT | PIGMENTED | WRINKLED",
  DRNW: "DRY | RESISTANT | NON-PIGMENTED | WRINKLED",
  DSPW: "DRY | SENSITIVE | PIGMENTED | WRINKLED",
  DSNW: "DRY | SENSITIVE | NON-PIGMENTED | WRINKLED",
  ORPT: "OILY | RESISTANT | PIGMENTED | TIGHT",
  ORNT: "OILY | RESISTANT | NON-PIGMENTED | TIGHT",
  OSPT: "OILY | SENSITIVE | PIGMENTED | TIGHT",
  OSNT: "OILY | SENSITIVE | NON-PIGMENTED | TIGHT",
  ORPW: "OILY | RESISTANT | PIGMENTED | WRINKLED",
  ORNW: "OILY | RESISTANT | NON-PIGMENTED | WRINKLED",
  OSPW: "OILY | SENSITIVE | PIGMENTED | WRINKLED",
  OSNW: "OILY | SENSITIVE | NON-PIGMENTED | WRINKLED",
};

export default mbtiTitle;
